### ISSUE TITLE
Créer un second repository pour l'interface administrateurs de BDD : Kib'admin

### ISSUE THREAD

**Issue by Franofarion** [LeMilliard/KiboDB#7]
J'y ai réfléchi, je compte faire kib'admin avec electron + vueJS. 
Ce sera un gestionnaire de base de données, l'objectif permettre de se connecter à une base Kiba et de modifier / créer des données. Plusieurs vues des données possibles, en tableau, en format JSON (voir l'appli Roboto).

Plus-value : prévoir la possibilité de se connecter à une base MongoDB, MySQL... et pouvoir faire une migration des données vers une base KibaDB, vice et versa.

**Comment by tkint** [comment]
Excellente idée. Par contre, pas forcément besoin d'un autre repo, une simple réorganisation de ce repo devrait suffire:
```
.
|__ kibo_core (KiboDB)
|    |__ src
|        |__ admin_api
|            |__ ...
|        |__ query_api
|            |__ ...
|        |__ config.py
|        |__ main.py
|    |__ .gitignore
|    |__ README.md
|    |__ requirements.txt
|__ kibo_client (Kib'Admin)
|    |__ ...
```
Qu'en penses-tu?

**Comment by Franofarion** [comment]
J'avais dans l'idée de créer une interface avec Electron assez générique
pour pouvoir se connecter à des bases KiboDB, MongoDB, MySQL, etc... Comme
ça on peut ajouter une fonctionnalité de migration MySQL -> KiboDB, et
inversement etc...

Le mieux serait d'en parler de vive voix


Baptiste Domange
Tel : 06 69 62 91 53
Mail : baptiste.domange@gmail.com
Site : www.baptiste-domange.fr <https://baptiste-domange.fr>
Linkedin : *www.linkedin.com/in/baptistedomange
<http://www.linkedin.com/in/baptistedomange>*



Le lun. 25 juin 2018 à 08:05, Thomas Kint <notifications@github.com> a
écrit :

**Comment by tkint** [comment]
Ok, donc faire un outil véritablement indépendant de KiboDB?

**Comment by tkint** [comment]
Tâche faite: https://github.com/LeMilliard/KibAdmin
